### ISSUE TITLE
Incorrect [replicationDenylist] stanza in distsearch.conf in 3.0.1 master

### ISSUE THREAD

**Issue by BartekZm** [splunk/Splunk-python-for-scientific-computing#1]
The recent change applied to 3.0.1 master in distsearch.conf seems to be incorrect - [replicationDenylist] is not a correct stanza for that config file as per spec. [replicationBlacklist] should be still in use:
https://docs.splunk.com/Documentation/Splunk/8.2.2/Admin/Distsearchconf#REPLICATION_DENY_LIST_OPTIONS

In result, this commit may be breaking the denylist functionality and may cause growth in KB size. It should be reverted:
https://github.com/splunk/Splunk-python-for-scientific-computing/commit/a1fd553d3e7eac3c0b8879dfd39fd65c89ff1f70

**Comment by andrew207** [comment]
Yes, I left a comment on that commit saying it broke all bundle replication in our search head cluster as the several gigabytes of binaries attempted to replicate to the indexers, exceeding the default bundleMaxSize limit causing bundle replication to stop entirely. 

+1 revert this change.
